# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://gitee.com/wtMal/malpodspecs.git'
source 'http://gitlab.meishubao.com/ArtPods/ArtFoundation.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'http://gitlab.meishubao.com/ArtPods/ArtPodRepo.git'
source 'https://github.com/aliyun/aliyun-specs.git'

target 'MPodTest' do
 
pod 'MNetMonitor', '~> 1.0.1'
pod 'MMenu'
pod 'ArtFoundation'

end
