# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://gitee.com/wtMal/malpodspecs.git'

target 'MRacDemo' do

pod 'ReactiveObjC', '~> 3.1.1'
pod 'MMenu'

end
