# Uncomment the next line to define a global platform for your project
#pod 源
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

use_modular_headers!

target 'MRxSwiftDemo' do

pod 'SnapKit'
pod 'RxSwift'
pod 'RxGesture', '3.0.1'

end
