source 'https://github.com/CocoaPods/Specs.git'


# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AILogManagerDemo' do
   use_frameworks!
   pod 'CocoaLumberjack/Swift'
end
