# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MLogSystemDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
 
  pod 'CocoaLumberjack', '~> 3.4.2'

  target 'MLogSystemDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MLogSystemDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
